In [1]:
import numpy as np

In [4]:
# 1 Reversed array
x = np.arange( 0, 10 )

In [9]:
y = x[::-1]

In [11]:
y

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
#2 

a = np.diag(y)

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
#3

import pandas as pd
ratings = pd.read_csv('ml-latest/ratings.csv')
ratings.head()

userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [45]:
ratings[ratings['rating'] == 5].groupby(['movieId','rating'])['rating'].agg(['count']).sort_values(['count'], ascending=False).head(1)

count
movieId rating       
318     5.0     45511

In [47]:
import pandas as pd
countries = pd.read_csv('power.csv')
countries.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [78]:
# 4
countries.query('country in ("Latvia","Lithuania","Estonia") & category in (4,12,21) & year >=2005 & year <= 2010').groupby('country')['quantity'].agg(['sum']).sort_values(['sum'],ascending=False)

sum
country            
Lithuania  122197.0
Estonia     63440.0
Latvia      54844.0

In [84]:
#5 Решение системы линейных уравнений
from numpy import linalg
aMatrix = np.matrix([[4,2,1],[1,3,0],[0,5,4]])

In [85]:
aMatrix

matrix([[4, 2, 1],
        [1, 3, 0],
        [0, 5, 4]])

In [86]:
b = np.array([4,12,-3])

In [87]:
b

array([ 4, 12, -3])

In [88]:
linalg.solve(aMatrix, b)

array([ 0.46666667,  3.84444444, -5.55555556])